'\nq1.\nHere are three different methods for creating identical 2D arrays in NumPy:\n\n### Method 1: Using `np.array()`\nYou can create a 2D array by passing a list of lists directly to the `np.array()` function.\n\n```python\nimport numpy as np\n\n# Method 1: Using np.array()\narray1 = np.array([[1, 2, 3], [4, 5, 6]])\n\nprint("Array using np.array():")\nprint(array1)\n```\n\n### Method 2: Using `np.zeros()` and assigning values\nYou can create a 2D array of zeros and then assign values manually.\n\n```python\n# Method 2: Using np.zeros() and assigning values\narray2 = np.zeros((2, 3), dtype=int)\narray2[0] = [1, 2, 3]\narray2[1] = [4, 5, 6]\n\nprint("\nArray using np.zeros() and manual assignment:")\nprint(array2)\n```\n\n### Method 3: Using `np.full()` with a predefined structure\nYou can use `np.full()` to fill an array with predefined values.\n\n```python\n# Method 3: Using np.full() and specifying values manually\narray3 = np.full((2, 3), 0)\narray3[0] = [1, 2, 3]\narray3[1] = [4

'\nq2.\nTo generate an array of evenly spaced numbers between two values (`w` and `wR`) and then reshape that array into a 2D array, you can use the following steps in NumPy:\n\n1. Use the `np.linspace()` function to generate `numPers` evenly spaced numbers between `w` and `wR`.\n2. Use the `reshape()` function to reshape the resulting 1D array into a 2D array.\n\nHere’s the code to demonstrate this process:\n\n```python\nimport numpy as np\n\n# Define your variables\nw = 0        # Starting point\nwR = 10      # Ending point\nnumPers = 12 # Total number of elements\nrows = 3     # Number of rows in the 2D array\ncols = 4     # Number of columns in the 2D array\n\n# Step 1: Generate 1D array with evenly spaced numbers\narray_1d = np.linspace(w, wR, numPers)\n\n# Step 2: Reshape the 1D array into a 2D array\narray_2d = array_1d.reshape(rows, cols)\n\nprint("1D array:")\nprint(array_1d)\n\nprint("\nReshaped 2D array:")\nprint(array_2d)\n```\n\n### Output:\n```\n1D array:\n[ 0.          0

'\nq3.\n### 1. Differences between `np.array()`, `np.asarray()`, and `np.asanyarray()`:\n\n#### **`np.array()`**:\n- **Creates a new array object** by copying the input data, even if the input is already an array.\n- Ensures that the returned object is a `numpy.ndarray`.\n- It will make a copy of the input data if needed.\n\n```python\nimport numpy as np\n\nlist_data = [1, 2, 3]\narray1 = np.array(list_data)  # Creates a new array from the list\n\nprint(array1)  # Output: [1 2 3]\n```\n\n#### **`np.asarray()`**:\n- **Converts input data to an array**, but **won’t copy the data** if the input is already an array-like object (e.g., a `numpy` array). \n- This is more efficient when working with large arrays that don\'t need to be copied.\n\n```python\narray2 = np.asarray(array1)  # No copy, returns the same array object\nprint(array2 is array1)  # Output: True (no new array is created)\n```\n\n#### **`np.asanyarray()`**:\n- Similar to `np.asarray()`, but it **allows subtypes of arrays** (

In [4]:
'''

### **1. Demonstrate three different methods for creating identical 2D arrays in NumPy:**

```python
import numpy as np

# Method 1: Using np.full
array1 = np.full((3, 3), 7)

# Method 2: Using np.ones and multiplication
array2 = np.ones((3, 3)) * 7

# Method 3: Using np.tile
array3 = np.tile(7, (3, 3))

print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nArray 3:\n", array3)
```

**Output:**

All methods will produce the same output:

```
Array 1:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Array 2:
 [[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]

Array 3:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]
```

---

### **2. Using the NumPy function, generate an array of 200 evenly spaced numbers between 0 and 50, and reshape that 1D array into a 2D array:**

```python
# Generate 200 evenly spaced numbers between 0 and 50
arr = np.linspace(0, 50, 200)

# Reshape the array into a 2D array of shape (20, 10)
reshaped_arr = arr.reshape(20, 10)

print("Reshaped 2D array:\n", reshaped_arr)
```

---

### **3. Explain the following terms:**

#### a) **The difference between `np.array`, `np.asarray`, and `np.asanyarray`:**

- `np.array`: Always creates a new array, regardless of the input type (even if it's already an array).

- `np.asarray`: Converts input to an array, but won’t copy the input if it's already an array.

- `np.asanyarray`: Similar to `np.asarray`, but if the input is a subclass of an array (e.g., `matrix`), it preserves the subclass.

#### b) **The difference between deep copy and shallow copy:**

- **Shallow Copy**: Copies the reference to the memory location, so changes to the original object affect the copy and vice versa.

- **Deep Copy**: Creates an entirely new object, copying both the object and any nested objects, so changes to the original object do not affect the copy.

---

### **4. Generate a 3x3 array with random floating-point numbers between 0 and 20, and round each number to 2 decimal places:**

```python
# Generate a 3x3 array with random floating-point numbers between 0 and 20
random_array = np.random.uniform(0, 20, (3, 3))

# Round each number to 2 decimal places
rounded_array = np.round(random_array, 2)

print("Rounded array:\n", rounded_array)
```

---

### **5. Create a NumPy array with random integers between 0 and 100 of shape (3, 3), then extract even and odd integers:**

```python
# Generate a 3x3 array with random integers between 0 and 100
int_array = np.random.randint(0, 100, (3, 3))

# a) Extract all even integers
even_integers = int_array[int_array % 2 == 0]

# b) Extract all odd integers
odd_integers = int_array[int_array % 2 != 0]

print("Original array:\n", int_array)
print("\nEven integers:\n", even_integers)
print("\nOdd integers:\n", odd_integers)
```

---

### **6. Create a 3D NumPy array of shape (3, 3, 3) containing random integers between 0 and 100, then perform operations:**

```python
# Create a 3D array with random integers
array_3d = np.random.randint(0, 100, (3, 3, 3))

# a) Find the indices of the maximum values along the third axis
max_indices = np.argmax(array_3d, axis=2)

# b) Element-wise multiplication between two arrays
array1 = np.random.randint(0, 100, (3, 3, 3))
array2 = np.random.randint(0, 100, (3, 3, 3))
elementwise_product = np.multiply(array1, array2)

print("3D array:\n", array_3d)
print("\nIndices of maximum values along the third axis:\n", max_indices)
print("\nElement-wise multiplication:\n", elementwise_product)
```

---

### **7. Clean and transform the 'Phone' column to remove non-numeric characters and convert it to a numeric type:**

```python
import pandas as pd

# Sample DataFrame
data = {'Name': ['John', 'Jane'], 'Phone': ['+1-234-567-890', '(555) 123-4567']}
df = pd.DataFrame(data)

# Remove non-numeric characters from the 'Phone' column
df['Phone'] = df['Phone'].str.replace(r'\D', '', regex=True)

# Convert to numeric data type
df['Phone'] = pd.to_numeric(df['Phone'])

# Display the attributes and data types of each column
print(df)
print("\nData types:\n", df.dtypes)
```

---

### **8. Perform tasks on a `people` dataset:**

```python
# a) Read the CSV file and skip the first 50 rows
df = pd.read_csv('data.csv', skiprows=50)

# b) Only read the specified columns
df_filtered = df[['Last Name', 'Gender', 'Email', 'Phone', 'Salary']]

# c) Display the first 10 rows of the filtered dataset
print(df_filtered.head(10))

# d) Extract 'Salary' column as a Series and display its last 5 values
salary_series = df_filtered['Salary']
print("\nLast 5 salaries:\n", salary_series.tail(5))
```



'\nq4.\nTo generate a 3x3 array with random floating-point numbers between 0 and 20, and then round each number to 2 decimal places, you can use the following steps in NumPy:\n\n1. Use `np.random.uniform()` to generate random floating-point numbers within a specified range.\n2. Use `np.round()` to round each number to 2 decimal places.\n\nHere’s the code to demonstrate this process:\n\n```python\nimport numpy as np\n\n# Step 1: Generate a 3x3 array with random floating-point numbers between 0 and 20\nrandom_array = np.random.uniform(0, 20, (3, 3))\n\n# Step 2: Round each number in the array to 2 decimal places\nrounded_array = np.round(random_array, 2)\n\nprint("Random 3x3 array with values between 0 and 20:")\nprint(random_array)\n\nprint("\nRounded array (to 2 decimal places):")\nprint(rounded_array)\n```\n\n### Example Output:\n\n```\nRandom 3x3 array with values between 0 and 20:\n[[ 8.5965604  11.90164348 15.2063203 ]\n [17.81731834  1.26848699 19.14719372]\n [12.36067334  5.94183